# Generated by Django 4.2.1 on 2024-02-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('entry_id', models.IntegerField()),
                ('field1', models.IntegerField()),
                ('field2', models.FloatField()),
                ('field3', models.FloatField()),
                ('field4', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
