# Generated by Django 4.2.1 on 2024-02-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_remove_sensordata_id_alter_sensordata_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='entry_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='field1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='field2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='field3',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
